In [2]:
#1 Extract all odd numbers from arr
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

In [5]:
#2 Replace all odd numbers in arr with -1
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
#3-Convert a 1D array to a 2D array with 2 rows
arr=np.arange(10)
arr=np.reshape(arr,(2,5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
#Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [53]:
#Get all items between 5 and 10 from a

a = np.array([2, 6, 1, 9, 10, 3, 27])
#a[a>=5,a<=10]
a[(a>5)&(a<10)]

array([6, 9])

In [39]:
#Create a null vector of size 10 but the fifth value which is 1.
z=np.zeros(10,int)
z[4]=1
z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [42]:
#Create a vector with values ranging from 10 to 49.
z2=np.arange(10,50)
z2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [45]:
#Create a 10x10 array with random values and find the minimum and maximum values.
z3=np.random.randint(low=1,high=50,size=(10,10))
z3.max()
z3.min()

1

In [51]:
#Create a 3*3 matrix and print it's transpose matrix
np.random.seed(0)
z4=np.random.randint(low=1,high=50,size=(3,3))
print(z4.transpose())


[[45  4 10]
 [48  4 20]
 [ 1 40 22]]


In [61]:
#Create two arrays of 2-D and find dot product of it.
m_a = np.array([[1,2],
               [2,1]])
m_b = np.array([[2,1],
               [1,2]])

np.dot(m_a,m_b)

array([[4, 5],
       [5, 4]])

In [68]:
#Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a.max(axis=1)


array([9, 8, 6, 3, 9])

In [71]:
#Select 3rd & 5th row and 3rd & 4th columns
data = np.random.randint(10,100,(5,4))
data[[2,4],2:4]

array([[66, 40],
       [74, 66]])

In [72]:
#Convert below matrix into vector
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
#The product of two inverse matrix is identical matrix,prove# create a square matrix

              
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
np.dot(m,n)

array([[1., 0.],
       [0., 1.]])

In [81]:
#Create a matrix from a uniform distribution over [0, 1)
np.random.seed(10)
a = np.random.rand(3,3)
a

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])