In [1]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
ten_zeroes = np.zeros(10)
ten_zeroes[4] = 1
print(ten_zeroes)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [3]:
ten_fortynine = np.arange(10,50)
print(ten_fortynine)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
mat = np.random.randint(0,8,(3,3))
mat

array([[6, 1, 6],
       [5, 4, 3],
       [2, 7, 0]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
index = np.nonzero([1,2,0,0,4,0])
index

(array([0, 1, 4], dtype=int64),)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
np.random.seed(7)

x= np.random.randint(0,100,(10,10))
print("Min value", x.min())
print("Max Value", x.max())

Min value 0
Max Value 99


# 6. Create a random vector of size 30 and find the mean value.

In [7]:
random = np.random.random(30)
random.mean()

0.5325093796254533